language: python
cache:
  pip: true
  directories:
    - I/usr/include/gtk-3.0
    - I/usr/include/at-spi2-atk/2.0
    - I/usr/include/at-spi-2.0
    - I/usr/include/dbus-1.0
    - I/usr/lib/x86_64-linux-gnu/dbus-1.0/include
    - I/usr/include/gtk-3.0
    - I/usr/include/gio-unix-2.0
    - I/usr/include/cairo
    - I/usr/include/libdrm
    - I/usr/include/pango-1.0
    - I/usr/include/harfbuzz
    - I/usr/include/pango-1.0
    - I/usr/include/fribidi
    - I/usr/include/atk-1.0
    - I/usr/include/cairo
    - I/usr/include/pixman-1
    - I/usr/include/freetype2
    - I/usr/include/libpng16
    - I/usr/include/gdk-pixbuf-2.0
    - I/usr/include/libmount
    - I/usr/include/blkid
    - I/usr/include/uuid
    - I/usr/include/glib-2.0
    - I/usr/lib/x86_64-linux-gnu/glib-2.0/include
matrix:
  include:
    - name: "Xenial Linux"
      python: 3.7
      dist: xenial
#    - name: "Windows"
#      os: windows
#      language: shell
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install gtk+-3.0
  - sudo apt-get install webkit2gtk-4.0

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script: python3 -m unittest discover -s tests