language: python
cache: pip
matrix:
  include:
    - name: "Xenial Linux"
      python: 3.7
      dist: xenial
#    - name: "Windows"
#      os: windows
#      language: shell
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install gtk+-3.0
  - sudo apt-get install webkit2gtk-4.0

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script: python3 -m unittest discover -s tests