language: python
matrix:
  include:
    - name: "Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script: python3 -m unittest discover -s tests